<?php
$bot_Token_Corte = '918836101:AAGGaH2MIoTjqdhOmRs_34G1Yjgx5VkwgFI';//TOKEN UNICO DEL BOT CORTES (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Corte = 'https://api.telegram.org/bot'.$bot_Token_Corte;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT
$bot_Token_Falla = '1284789530:AAGhC_vfTpyElbPA4pHkyNoPe7PvdxV1Vpo';//TOKEN UNICO DEL BOT CORTES (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Falla = 'https://api.telegram.org/bot'.$bot_Token_Falla;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT
$bot_Token_Resumen = '1353311525:AAEv95sHfBzsyK3WNVSkBRXxm6wqcIgHoTY';//TOKEN UNICO DEL BOT RESUMEN_FALLAS (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Resumen = 'https://api.telegram.org/bot'.$bot_Token_Resumen;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT

$id_Chat_Fredy = '1087049979';//ID Fredy ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Gabriel = '1080437366';//ID Gabriel ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Mayra = '1436846239';//ID Mayra ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Luis = '972701200'; //ID Luis ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
