<?php
#$bot_Token_Corte = '918836101:AAGGaH2MIoTjqdhOmRs_34G1Yjgx5VkwgFI';//TOKEN UNICO DEL BOT CORTES (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$bot_Token_Corte2 = '1652202112:AAHyH8NzDJfP4XIMSUXNv-04Se7zORNLnkI';//TOKEN UNICO DEL BOT CORTES2 (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Corte = 'https://api.telegram.org/bot'.$bot_Token_Corte2;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT
#$bot_Token_Falla = '1284789530:AAGhC_vfTpyElbPA4pHkyNoPe7PvdxV1Vpo';//TOKEN UNICO DEL BOT Check_Red (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$bot_Token_Falla2 = '1660306414:AAEJI_IyVI4zGUz0FJk4_wA0h6Sg0UqOhtw';//TOKEN UNICO DEL BOT CheckRed2 (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Falla = 'https://api.telegram.org/bot'.$bot_Token_Falla2;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT
#$bot_Token_Resumen = '1353311525:AAEv95sHfBzsyK3WNVSkBRXxm6wqcIgHoTY';//TOKEN UNICO DEL BOT RESUMEN_FALLAS (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$bot_Token_Resumen2 = '1616528291:AAHIrcqVTS4tikzivUWjbOiOlNO_IFWjwNo';//TOKEN UNICO DEL BOT RESUMENFALLAS2 (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Resumen = 'https://api.telegram.org/bot'.$bot_Token_Resumen2;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT 
$bot_Token_Aviso = '1665157082:AAHYjoi1Rbp4BGjR48L0YqlaJsfdp3dwbaw';//TOKEN UNICO DEL BOT AVISO CORTES (ID PARA IDENTIFICAR AL BOT Y PODER ENVIAR EL MENSAJE DESDE EL BOT)
$website_Aviso = 'https://api.telegram.org/bot'.$bot_Token_Aviso;//DIRECCION A LA QUE SE TIENE QUE ACCEDER LA FUNCION PARA PODER ENVIAR EL MENSAJE DESDE EL BOT 

$id_Chat_Fredy = '1087049979';//ID Fredy ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Gabriel = '1080437366';//ID Gabriel ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Mayra = '1436846239';//ID Mayra ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Luis = '972701200'; //ID Luis ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
$id_Chat_Rocio = '1591378882'; //ID Luis ES COMO UN NUMERO TELEFONICO CON EL QUE EL BOT IDENTIFICA A QUIEN ENVIAR EL MENSAJE
